version: 2
registries:
  maven:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
    registries:
      - "maven"
    groups:
      maven:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/my-app"
    schedule:
      interval: "daily"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github:
        patterns:
          - "*"
