version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
    groups:
      maven:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/my-app"
    schedule:
      interval: "daily"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github:
        patterns:
          - "*"
