version: 2
registries:
  mvn:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt
    username: x-access-token
    password: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    registries:
      - mvn
    groups:
      maven:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      workflows:
        patterns:
          - "*"
  - package-ecosystem: npm
      directory: "/"
      schedule:
        interval: daily
      groups:
        maven:
          patterns:
            - "*"
