name: Automerge Dependabot PRs

on:
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Automerge Dependabot PRs
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ steps.app-token.outputs.token }}
          minimum-age-of-pr: '0'
          ignored-dependencies: path-to-regexp@*,express,react-dom@19.1.0, react@19.1.0
          semver-filter: minor,patch,major
          merge-method: squash
