name: Dispatch octo-sts reusable
on:
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: navikt/appsec-public-test/.github/workflows/sts-reusable.yaml@main
