name: Build gradle app with READER_TOKEN
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@8379f6a1328ee0e06e2bb424dadb7b159856a326 # v4.4.0
      - name: Generate sbom
        run: ./gradlew cyclonedxBom
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Gradle build
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}