name: Reusable workflows test
on:
  workflow_dispatch:

jobs:
  build:
    uses: navikt/.github/.github/workflows/gradle-build.yaml@main
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      team: appsec
  scan:
    uses: navikt/.github/.github/workflows/trivy.yaml@main
    permissions:
      contents: write
      security-events: write
      id-token: write
    secrets: inherit
    with:
      team: appsec
  
