name: Reusable workflows test
on:
  workflow_dispatch:

jobs:
  build:
    uses: navikt/workflows/.github/workflows/build-gradle.yaml@main
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      team: appsec
  scan:
    uses: navikt/workflows/.github/workflows/trivy.yaml@main
    permissions:
      contents: write
      security-events: write
      id-token: write
    secrets: inherit
    with:
      team: appsec
      image: ${{ needs.build.outputs.image }}
