name: (Reusable) Build gradle app with octo-sts token
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # for octo-sts
    steps:
      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05
        id: octo-sts
        with:
          scope: navikt/appsec-internal-test
          identity: readpkgs
#      - name: gh login
#        run: echo ${{ steps.octo-sts.outputs.token }} | gh auth login --with-token
#      - name: check token status
#        run: |
#          gh api \
#          -H "Accept: application/vnd.github+json" \
#          -H "X-GitHub-Api-Version: 2022-11-28" \
#          "/orgs/navikt/packages?package_type=maven"
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
      - name: Generate sbom
        run: ./gradlew cyclonedxBom
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      - name: Gradle build
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
